### ISSUE TITLE
Marketing: How to market this product?

### ISSUE THREAD

**Issue by nubpro** [nubpro/nakvaksin#12]
How can we spread the word?

List your suggestions in the comment space

**Comment by nubpro** [comment]
Perhaps show them a share button after subscribing to our service.
The shared post will include a message like "I am subscribed to NakVaksin to get my vax status, have you?" blah something like that

**Comment by chengkangzai** [comment]
1. Social Media engagement 
--> Twitter, Facebook, Instagram account
--> On the Share button, tag the social media account

**Comment by chengkangzai** [comment]
2. Make the software even more SEO friendly 
--> by making use of meta tag 
--> Addition: maybe can make use of google analytic to find the area of improve

**Comment by nubpro** [comment]
> 1. Make the software even more SEO friendly
>    --> by making use of meta tag
>    --> Addition: maybe can make use of google analytic to find the area of improve

Definitely need to work on this asap
