### ISSUE TITLE
[FE] Feat: Adapt React Query as a Caching Strategy and global state management

### ISSUE THREAD

**Issue by chengkangzai** [nubpro/nakvaksin#16]
## Problem statement

Improve the speed of the website and reduce the api call 

## Proposed work

Using React Query to cache the api and control the global state

# Success criteria

The criteria that must be met in order to consider this project a success. 

- to be determine 

# User stories

How the product should work for various user types.

## Normal User

- Feel fast UI

# Related documents

Include links to other pages as necessary (e.g. technical design doc, project proposal, etc.)

[https://react-query.tanstack.com/overview](https://react-query.tanstack.com/overview)

**Comment by chengkangzai** [comment]
@nubpro let me know what do you think :3

**Comment by nubpro** [comment]
> @nubpro let me know what do you think :3

hmm I'm not sure what to say hahaa, lets do it?

**Comment by chengkangzai** [comment]
Anything to added on? xD

**Comment by nubpro** [comment]
> Anything to added on? xD

No nothing in mind actually

**Comment by nubpro** [comment]
I think this should be closed since we have successfully implemented RQ into our app
