### ISSUE TITLE
Additional API

### ISSUE THREAD

**Issue by mshuflin** [nubpro/nakvaksin#56]
The API endpoints listed (login, profile, vaccine, and forgot password) are great. Any chance you have worked out some additional locations for curl? For example:

- GET check-in history
- POST check-out
- "Covid-19 Status" form (to update health status)
- Depedent profile information (e.g. risk status)

**Comment by nubpro** [comment]
> * GET check-in history

To my knowledge, there is no public API to retrieve user's past check-ins

For the rest, may I suggest that you can achieve them by installing a proxy agent on your device. For iOS, I use Proxyman to capture the traffic requests.
As your request is out of the scope of this project, I wont be exploring them. Sorry!
